---
- name: 在节点创建相关目录
  file: name={{ item }} state=directory
  with_items:
  - /etc/kubernetes/addon/

- name: 配置 metrics-server yaml文件
  template: src=metrics-server.yaml.j2 dest=/etc/kubernetes/addon/metrics-server.yaml

# 只需单节点执行一次
- name: 创建 metrics-server
  shell: "kubectl apply -f /etc/kubernetes/addon/metrics-server.yaml"
  run_once: true
