---
- name: 创建etcd相关目录
  file: 
    name: "{{ item }}"
    state: directory
  with_items:
  - "{{ TLS_DIR }}" 
  - "{{ ETCD_DIR }}/bin"
  - "{{ ETCD_DIR }}/data"
  - "{{ ETCD_DIR }}/backup"

- name: 分发etcd二进制文件
  get_url:
    url: "{{ etcd_url }}/{{ item }}"
    dest: "{{ ETCD_DIR }}/bin"
    mode: u+x
  with_items:
    - etcd
    - etcdctl

- name: 下发etcd 证书
  copy:
    src: "{{ pki_dir }}/{{ item }}"
    dest: "{{ TLS_DIR }}"
  with_items:
    - ca.pem
    - etcd.pem
    - etcd-key.pem

- name: 创建etcd的systemd unit文件
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service

- name: 启动etcd并设置成开机启动
  service:
    name: etcd 
    state: started 
    enabled: yes 
    daemon_reload: yes
  ignore_errors: true

- name: 开启etcd服务
  shell:  systemctl restart etcd
  args:
    executable: bash
  ignore_errors: true

- name: 以轮询的方式等待服务同步完成
  shell: "systemctl status etcd.service|grep Active"
  register: etcd_status
  until: '"running" in etcd_status.stdout'
  retries: 8
  delay: 8
