---
- name: 在节点创建相关目录
  file: name={{ item }} state=directory
  with_items:
  - /etc/kubernetes/addon/

- name: 配置 coredns yaml文件
  template: src=coredns.yaml.j2 dest=/etc/kubernetes/addon/coredns.yaml

# 只需单节点执行一次
- name: 创建coredns
  shell: "kubectl apply -f /etc/kubernetes/addon/coredns.yaml"
  run_once: true
