- name: 安装docker-ce
  yum:
    name: docker-ce-{{ docker.version }}
  ignore_errors: true

- name: 创建docker配置目录
  file: name=/etc/docker state=directory

- name: 创建docker 镜像仓库证书目录
  file: name="/etc/docker/certs.d/{{ HARBOR.url }}:443" state=directory
  when: HARBOR.url is defined

- name: docker命令自动补全
  copy: src="{{ HARBOR.crt }}" dest="/etc/docker/certs.d/{{ HARBOR.url }}:443" mode=0644
  when: HARBOR.crt is defined

- name: 分发docker配置文件
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json

#- name: 创建docker的systemd unit文件
#  template: src=docker.service.j2 dest=/etc/systemd/system/docker.service

- name: 检查补全脚本存在否
  stat: path=/etc/bash_completion.d/docker
  register: check_completion_files

- name: docker命令自动补全
  copy: src=docker dest=/etc/bash_completion.d/docker mode=0644
  when: not check_completion_files.stat.exists

- name: 设置开机并启动docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Replace a localhost entry with our own
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ HARBOR.ip }}'
    line: '{{ HARBOR.ip }} {{ HARBOR.url }}'
    owner: root
    group: root
    mode: '0644'
  when: HARBOR.url is defined

- name: Replace a namserver entry with our own
  lineinfile:
    path: /etc/resolv.conf
    regexp: '10.200.41.54'
    state: absent
  when: HARBOR.url is defined

- name: Replace a namserver entry with our own
  lineinfile:
    path: /etc/resolv.conf
    insertbefore: 'nameserver'
    line: 'nameserver 10.200.41.54'
    owner: root
    group: root
    mode: '0644'
  when: HARBOR.url is defined

- name: Login {{ HARBOR.url }}
  shell: docker login -u {{ HARBOR.user }} -p {{ HARBOR.pass }}  {{ HARBOR.url }}:443
  ignore_errors: true
  when: HARBOR.url is defined
